/**
 * jira-openclaw-plugin — OpenClaw native plugin entry (0.4.0).
 *
 * 11 named tools via `defineToolPlugin` (OpenClaw 0.5.17+). Manifest
 * generated by `openclaw plugins build` keeps runtime registry in sync.
 *
 * Reads ATST_TOKEN / JIRA_CLOUD_ID / JIRA_PROXY from env (with optional
 * openclaw.json config override) — see auth.ts for resolution order.
 * Orchestrator tools also read JIRA_DEFAULT_ASSIGNEE_ACCOUNT_ID (optional,
 * used as the implicit assignee for create_task / create_subtask).
 */
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { setPluginConfig } from "./auth.js";
import { search } from "./handlers/search.js";
import { get } from "./handlers/get.js";
import { comment } from "./handlers/comment.js";
import { listComments } from "./handlers/list_comments.js";
import { getComment } from "./handlers/get_comment.js";
import { createTask } from "./handlers/create_task.js";
import { createSubtask } from "./handlers/create_subtask.js";
import { submitVerdict } from "./handlers/submit_verdict.js";
import { abandonTask } from "./handlers/abandon_task.js";
import { requestHelp } from "./handlers/request_help.js";
import { transition } from "./handlers/transition.js";
import { listAttachments } from "./handlers/list_attachments.js";
import { getAttachment } from "./handlers/get_attachment.js";
import { uploadAttachment } from "./handlers/upload_attachment.js";

/**
 * Bridge plugin config (from openclaw.json) into the module-level state
 * that handlers read via loadConfig(). Each tool calls this at the start
 * of execute() so config overrides are picked up at the latest possible
 * moment, even if openclaw.json is updated after plugin load.
 */
function applyConfig(config: unknown): void {
  setPluginConfig((config as Record<string, unknown> | null) ?? null);
}

export default defineToolPlugin({
  id: "jira-openclaw-plugin",
  name: "Jira",
  description:
    "Jira Cloud REST v3 native tools (11 methods, each is a named tool). Generic: jira_search / jira_get / jira_list_comments / jira_get_comment / jira_comment / jira_transition. Orchestrator: jira_create_task / jira_create_subtask / jira_submit_verdict / jira_abandon_task / jira_request_help. Reads ATST_TOKEN / JIRA_CLOUD_ID / JIRA_PROXY from env. See skills/jira/SKILL.md for per-tool guidance.",
  configSchema: Type.Object({
    atstToken: Type.Optional(
      Type.String({ description: "(optional) Override ATST_TOKEN env var" }),
    ),
    cloudId: Type.Optional(
      Type.String({ description: "(optional) Override JIRA_CLOUD_ID env var" }),
    ),
    proxy: Type.Optional(
      Type.String({ description: "(optional) Override JIRA_PROXY env var" }),
    ),
  }),
  tools: (tool) => [
    tool({
      name: "jira_search",
      label: "Jira Search",
      description:
        "JQL search. Default 30 results. Returns matching tickets with summary/status/labels/created/parent.",
      parameters: Type.Object({
        jql: Type.String({ description: "JQL query string" }),
        maxResults: Type.Optional(
          Type.Number({ description: "Max results, default 30" }),
        ),
        fields: Type.Optional(
          Type.Array(Type.String(), { description: "Fields to include" }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await search(params);
      },
    }),
    tool({
      name: "jira_get",
      label: "Jira Get",
      description:
        "Read single ticket details by key (e.g. 'WTO-100'). Default fetches only a whitelisted set of 12 fields (summary/status/issuetype/priority/labels/assignee/reporter/created/updated/parent/description/issuelinks) — this excludes the heavy `comment` and `worklog` sub-resources (5-50 KB per call). Pass `fields: ['*all']` for the full payload, or a specific list like `['customfield_10019']` to scope to one field. Comments should be fetched separately via jira_list_comments.",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key like 'WTO-100'" }),
        fields: Type.Optional(
          Type.Array(Type.String(), {
            description:
              "Field names to fetch server-side. Empty / omitted = default whitelist (efficient). Pass ['*all'] for full payload, or e.g. ['customfield_10019'] to scope to one field.",
          }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await get(params);
      },
    }),
    tool({
      name: "jira_list_comments",
      label: "Jira List Comments",
      description:
        "List comments on a ticket. Comment bodies are rendered to plain text (no ADF). Optional startAt / maxResults (default 50, max 100) / orderBy ('created' | '-created', default '-created') / since (ISO date, client-side filter on created>=since) / authorAccountId (client-side filter on author.accountId).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key" }),
        startAt: Type.Optional(
          Type.Number({ description: "Pagination offset, default 0" }),
        ),
        maxResults: Type.Optional(
          Type.Number({
            description: "Max comments to return, default 50, max 100",
          }),
        ),
        orderBy: Type.Optional(
          Type.String({
            description: "'created' or '-created', default '-created'",
          }),
        ),
        since: Type.Optional(
          Type.String({
            description:
              "Optional ISO date string (e.g. '2026-06-15' or '2026-06-15T10:00:00.000+0800'). Client-side filter: keep comments with created>=since. Empty/omitted = no filter.",
          }),
        ),
        authorAccountId: Type.Optional(
          Type.String({
            description:
              "Optional account id (e.g. '712020:42e79d90-...'). Client-side filter: keep comments whose author.accountId matches. Empty/omitted = no filter.",
          }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await listComments(params);
      },
    }),
    tool({
      name: "jira_get_comment",
      label: "Jira Get Comment",
      description:
        "Read a single comment by id. Both issueIdOrKey AND commentId are required. Body is rendered to plain text (no ADF).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key" }),
        commentId: Type.String({
          description: "Comment id (numeric string from jira_list_comments)",
        }),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await getComment(params);
      },
    }),
    tool({
      name: "jira_comment",
      label: "Jira Comment",
      description:
        "Add a plain-text comment to a ticket. Body is a string — NOT ADF. Plugin auto-wraps into ADF internally. Use `\\n` for line breaks. Optional `mentionAccountIds` to @mention users (string[] of accountIds).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key" }),
        body: Type.String({ description: "Comment body (plain text). Use \\n for line breaks. Plugin auto-wraps to ADF." }),
        mentionAccountIds: Type.Optional(
          Type.Array(Type.String(), {
            description: "Optional list of Atlassian accountIds to @mention in this comment.",
          }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await comment(params);
      },
    }),
    tool({
      name: "jira_create_task",
      label: "Jira Create Task",
      description:
        "Create a main task. Locks template + plan label + assignee. requirements / scope / acceptance_criteria are 3 plain-text strings (NOT ADF dict, NOT arrays) — plugin wraps them into the 3-section description template. scope (按 labels.md 写 ✅/❌ 负责) 必填.",
      parameters: Type.Object({
        project: Type.String({ description: "Project key, e.g. 'WTO'" }),
        summary: Type.String({ description: "Task summary" }),
        requirements: Type.String({
          description:
            "Plain text string (NOT ADF dict). 任务说明 段正文. Use \\n for line breaks.",
        }),
        scope: Type.String({
          description:
            "Plain text string. ✅ 负责 / ❌ 不负责 scope text per labels.md.",
        }),
        acceptance_criteria: Type.String({
          description:
            "Plain text string (NOT string[]). 验收标准 段正文, e.g. 'AC1: ...\\nAC2: ...\\nAC3: ...'.",
        }),
        labels: Type.Optional(
          Type.Array(Type.String(), {
            description: "Additional labels (plan label is auto-added)",
          }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await createTask(params);
      },
    }),
    tool({
      name: "jira_create_subtask",
      label: "Jira Create Subtask",
      description:
        "Create a subtask under parent. Locks template + label + assignee + optional block. requirements / scope / acceptance_criteria are 3 plain-text strings (NOT ADF dict, NOT arrays). scope 必填. labels 必填 (no default).",
      parameters: Type.Object({
        project: Type.String({ description: "Project key" }),
        parent: Type.String({ description: "Parent issue key" }),
        summary: Type.String({ description: "Subtask summary" }),
        requirements: Type.String({
          description:
            "Plain text string (NOT ADF dict). 任务说明 段正文.",
        }),
        scope: Type.String({
          description: "Plain text string. ✅/❌ 职责 scope text.",
        }),
        acceptance_criteria: Type.String({
          description:
            "Plain text string (NOT string[]). 验收标准 段正文.",
        }),
        labels: Type.Array(Type.String(), {
          description: "Required. e.g. ['code'], ['test'], ['ops']",
        }),
        block: Type.Optional(
          Type.Object(
            {
              blockedBy: Type.Optional(Type.Array(Type.String())),
              blocks: Type.Optional(Type.Array(Type.String())),
            },
            { description: "Optional dependency links" },
          ),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await createSubtask(params);
      },
    }),
    tool({
      name: "jira_submit_verdict",
      label: "Jira Submit Verdict",
      description:
        "⚠️ ATOMIC — 一次调用即关闭 ticket，不需要再额外调用 jira_transition。verdict=PASS: 自动发评论 + 转「已完成」; verdict=FAIL: 自动发评论 + 加 escalated label + 清 assignee。reason 必填 (FAIL 时). 调完别再 transition 会覆盖已转好的状态。",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key" }),
        verdict: Type.Union(
          [Type.Literal("PASS"), Type.Literal("FAIL")],
          { description: "Verdict" },
        ),
        summary: Type.String({ description: "Verdict summary" }),
        reason: Type.Optional(
          Type.String({
            description: "Required when verdict=FAIL. Documents why it failed.",
          }),
        ),
        evidence: Type.Optional(
          Type.String({ description: "Optional evidence/screenshot path" }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await submitVerdict(params);
      },
    }),
    tool({
      name: "jira_abandon_task",
      label: "Jira Abandon Task",
      description:
        "Abandon a subtask (re-planning). 评论 + 清 assignee + 转「已完成」+ 清 escalated label by default. Subtask-only (main task → submit_verdict).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Subtask issue key" }),
        reason: Type.String({ description: "Why abandoning" }),
        labels: Type.Optional(
          Type.Array(Type.String(), {
            description:
              "Labels to remove after transition succeeds. Defaults to ['escalated'].",
          }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await abandonTask(params);
      },
    }),
    tool({
      name: "jira_request_help",
      label: "Jira Request Help",
      description:
        "Main task asks a human for guidance. 评论 + wait-approval label + 清 assignee. Main-task-only (subtask → submit_verdict FAIL).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Main task issue key" }),
        question: Type.String({ description: "Question to ask the human" }),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await requestHelp(params);
      },
    }),
    tool({
      name: "jira_transition",
      label: "Jira Transition",
      description:
        "⚠️ 调试/人为干预专用 — 正常 ticket 生命周期请用 jira_submit_verdict（PASS/FAIL 自动 close）。普通 agent 不应主动调本方法（会绕过 verdict 流程 + 丢失审计），仅 cereb-pilot dispatcher 或 Leo 手动修复 stuck state 时使用。Logical names: 'todo' / 'in_progress' / 'done' / 'review' / 'blocked' / 'reopen' / 'cancelled' (project-agnostic). Falls back to exact project status name.",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key" }),
        targetStatus: Type.String({
          description:
            "Logical name (preferred): 'todo' / 'in_progress' / 'done' / 'review' / 'blocked' / 'reopen' / 'cancelled'. Or pass the project's exact status name as last-resort fallback.",
        }),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await transition(params);
      },
    }),
    tool({
      name: "jira_list_attachments",
      label: "Jira List Attachments",
      description:
        "List ALL attachment metadata on a ticket (no cap). Use when jira_get's `moreCount: N` indicates there are unlisted attachments, or when you need a full enumeration. Returns [{id, filename, size, mimeType, content URL, thumbnail URL, author, created}, ...]. NO file content — use jira_get_attachment for the actual bytes.",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key like 'SSSS-432'" }),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await listAttachments(params);
      },
    }),
    tool({
      name: "jira_get_attachment",
      label: "Jira Get Attachment",
      description:
        "Download an attachment's binary content to disk. Returns the saved file path (NOT base64 — that would balloon LLM context for large files). Default save path: /tmp/openclaw-attachments/{id}.{ext} (not inside the OpenClaw system dir). Use `saveToPath` to override. Call jira_list_attachments first to get the attachmentId for the file you want.",
      parameters: Type.Object({
        attachmentId: Type.String({
          description:
            "Attachment id (string from jira_list_attachments or jira_get.attachments[].id).",
        }),
        saveToPath: Type.Optional(
          Type.String({
            description:
              "Optional full file path to save to. Default: /tmp/openclaw-attachments/{id}.{ext} derived from mimeType. Caller is responsible for ensuring the dir exists when overriding.",
          }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await getAttachment(params);
      },
    }),
    tool({
      name: "jira_upload_attachment",
      label: "Jira Upload Attachment",
      description:
        "Upload a single local file to a Jira issue. Pass an absolute `filePath`; the plugin reads the file and POSTs it as a multipart/form-data attachment. 100 MB hard cap (Atlassian Cloud per-file limit). Returns the created attachment metadata (id, filename, size, mimeType, content URL).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key like 'SSSS-454'" }),
        filePath: Type.String({
          description:
            "Absolute path to the file to upload (server-side). Plugin reads from disk and uploads the bytes; the filename on Jira is basename(filePath).",
        }),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await uploadAttachment(params);
      },
    }),
  ],
});
