/**
 * jira-openclaw-plugin — OpenClaw native plugin entry (0.4.0).
 *
 * 9 named tools via `defineToolPlugin` (OpenClaw 0.5.17+). Manifest
 * generated by `openclaw plugins build` keeps runtime registry in sync.
 *
 * Reads ATST_TOKEN / JIRA_CLOUD_ID / JIRA_PROXY from env (with optional
 * openclaw.json config override) — see auth.ts for resolution order.
 * Orchestrator tools also read JIRA_DEFAULT_ASSIGNEE_ACCOUNT_ID (optional,
 * used as the implicit assignee for create_task / create_subtask).
 */
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { setPluginConfig } from "./auth.js";
import { search } from "./handlers/search.js";
import { get } from "./handlers/get.js";
import { comment } from "./handlers/comment.js";
import { createTask } from "./handlers/create_task.js";
import { createSubtask } from "./handlers/create_subtask.js";
import { submitVerdict } from "./handlers/submit_verdict.js";
import { abandonTask } from "./handlers/abandon_task.js";
import { requestHelp } from "./handlers/request_help.js";
import { transition } from "./handlers/transition.js";

/**
 * Bridge plugin config (from openclaw.json) into the module-level state
 * that handlers read via loadConfig(). Each tool calls this at the start
 * of execute() so config overrides are picked up at the latest possible
 * moment, even if openclaw.json is updated after plugin load.
 */
function applyConfig(config: unknown): void {
  setPluginConfig((config as Record<string, unknown> | null) ?? null);
}

export default defineToolPlugin({
  id: "jira-openclaw-plugin",
  name: "Jira",
  description:
    "Jira Cloud REST v3 native tools (9 methods, each is a named tool). Generic: jira_search / jira_get / jira_comment / jira_transition. Orchestrator: jira_create_task / jira_create_subtask / jira_submit_verdict / jira_abandon_task / jira_request_help. Reads ATST_TOKEN / JIRA_CLOUD_ID / JIRA_PROXY from env. See skills/jira/SKILL.md for per-tool guidance.",
  configSchema: Type.Object({
    atstToken: Type.Optional(
      Type.String({ description: "(optional) Override ATST_TOKEN env var" }),
    ),
    cloudId: Type.Optional(
      Type.String({ description: "(optional) Override JIRA_CLOUD_ID env var" }),
    ),
    proxy: Type.Optional(
      Type.String({ description: "(optional) Override JIRA_PROXY env var" }),
    ),
  }),
  tools: (tool) => [
    tool({
      name: "jira_search",
      label: "Jira Search",
      description:
        "JQL search. Default 30 results. Returns matching tickets with summary/status/labels/created/parent.",
      parameters: Type.Object({
        jql: Type.String({ description: "JQL query string" }),
        maxResults: Type.Optional(
          Type.Number({ description: "Max results, default 30" }),
        ),
        fields: Type.Optional(
          Type.Array(Type.String(), { description: "Fields to include" }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await search(params);
      },
    }),
    tool({
      name: "jira_get",
      label: "Jira Get",
      description: "Read single ticket details by key (e.g. 'WTO-100').",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key like 'WTO-100'" }),
        fields: Type.Optional(
          Type.Array(Type.String(), { description: "Fields to include" }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await get(params);
      },
    }),
    tool({
      name: "jira_comment",
      label: "Jira Comment",
      description:
        "Add a comment to a ticket. Body MUST be an ADF dict (not a plain string): {version:1, type:'doc', content:[{type:'paragraph', content:[{type:'text', text:'...'}]}]}. For @mention use ADF mention nodes + mentionMap (strict bijection).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key" }),
        body: Type.Object(
          {
            version: Type.Literal(1),
            type: Type.Literal("doc"),
            content: Type.Array(
              Type.Object({}, { additionalProperties: true }),
            ),
          },
          { description: "ADF document" },
        ),
        mentionMap: Type.Optional(
          Type.Record(Type.String(), Type.String(), {
            description:
              "Optional {name: accountId} map. Plugin enforces strict bijection with ADF mention nodes.",
          }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await comment(params);
      },
    }),
    tool({
      name: "jira_create_task",
      label: "Jira Create Task",
      description:
        "Create a main task. Locks template + plan label + assignee. scope (按 labels.md 写 ✅/❌ 负责) 必填, 主任务 + 子任务 description 都会渲染 ## 职责范围 节.",
      parameters: Type.Object({
        project: Type.String({ description: "Project key, e.g. 'WTO'" }),
        summary: Type.String({ description: "Task summary" }),
        requirements: Type.String({ description: "Task requirements" }),
        scope: Type.String({
          description: "✅ 负责 / ❌ 不负责 scope text",
        }),
        acceptance_criteria: Type.Array(Type.String(), {
          description: "List of acceptance criteria strings",
        }),
        labels: Type.Optional(
          Type.Array(Type.String(), {
            description: "Additional labels (plan label is auto-added)",
          }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await createTask(params);
      },
    }),
    tool({
      name: "jira_create_subtask",
      label: "Jira Create Subtask",
      description:
        "Create a subtask under parent. Locks template + label + assignee + optional block. scope 必填. labels 必填 (no default).",
      parameters: Type.Object({
        project: Type.String({ description: "Project key" }),
        parent: Type.String({ description: "Parent issue key" }),
        summary: Type.String({ description: "Subtask summary" }),
        requirements: Type.String({ description: "Subtask requirements" }),
        scope: Type.String({ description: "✅/❌ 职责 scope text" }),
        acceptance_criteria: Type.Array(Type.String(), {
          description: "List of acceptance criteria strings",
        }),
        labels: Type.Array(Type.String(), {
          description: "Required. e.g. ['code'], ['test'], ['ops']",
        }),
        block: Type.Optional(
          Type.Object(
            {
              blockedBy: Type.Optional(Type.Array(Type.String())),
              blocks: Type.Optional(Type.Array(Type.String())),
            },
            { description: "Optional dependency links" },
          ),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await createSubtask(params);
      },
    }),
    tool({
      name: "jira_submit_verdict",
      label: "Jira Submit Verdict",
      description:
        "Close out a task. verdict=PASS 评论 + 转「已完成」; verdict=FAIL 评论 + escalated label + 清 assignee. reason 必填 (FAIL 时).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key" }),
        verdict: Type.Union(
          [Type.Literal("PASS"), Type.Literal("FAIL")],
          { description: "Verdict" },
        ),
        summary: Type.String({ description: "Verdict summary" }),
        reason: Type.Optional(
          Type.String({
            description: "Required when verdict=FAIL. Documents why it failed.",
          }),
        ),
        evidence: Type.Optional(
          Type.String({ description: "Optional evidence/screenshot path" }),
        ),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await submitVerdict(params);
      },
    }),
    tool({
      name: "jira_abandon_task",
      label: "Jira Abandon Task",
      description:
        "Abandon a subtask (re-planning). 评论 + 清 assignee + 转「已完成」. Subtask-only (main task → submit_verdict).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Subtask issue key" }),
        reason: Type.String({ description: "Why abandoning" }),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await abandonTask(params);
      },
    }),
    tool({
      name: "jira_request_help",
      label: "Jira Request Help",
      description:
        "Main task asks a human for guidance. 评论 + wait-approval label + 清 assignee. Main-task-only (subtask → submit_verdict FAIL).",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Main task issue key" }),
        question: Type.String({ description: "Question to ask the human" }),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await requestHelp(params);
      },
    }),
    tool({
      name: "jira_transition",
      label: "Jira Transition",
      description:
        "Transition a ticket to a target status by status name (e.g. 'In Progress', 'Done', '已完成'). Not by transition button label.",
      parameters: Type.Object({
        issueIdOrKey: Type.String({ description: "Issue key" }),
        targetStatus: Type.String({ description: "Target status name" }),
      }),
      async execute(params, config) {
        applyConfig(config);
        return await transition(params);
      },
    }),
  ],
});
